version: "3.5"

networks:
  pgadmin:

volumes:
  pgadmin:

secrets:
  pgadmin_admin_password:
    name: ${STACK_NAME:-technocore}_pgadmin_admin_password
    external: true

services:
  ## Uncomment this if Traefik will be used for routing traffick to this service.
  ingress:
    networks:
      - pgadmin

  pgadmin:
    deploy:
      labels:
        - traefik.frontend.rule=$PGADMIN_ROUTING_LABEL
        - traefik.frontend.priority=$PGADMIN_ROUTING_LABEL_PRIORITY
        - traefik.port=80
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_pgadmin
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      # Sometimes you have to pass in ${DOMAIN} to enable the correct link paths to be generated.
      # Othertimes you can use http:// or https:// for the website. Weird trick.
      - ADMIN_USER=${ADMIN_USER}
      - PGADMIN_DEFAULT_EMAIL=technocore@${DOMAIN}
      - PGADMIN_DEFAULT_PASSWORD={{"{{DOCKER-SECRET:admin_password}}"}}
    image: ${image_provider:-scififarms}/technocore-pgadmin:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - pgadmin
    secrets:
      - source: pgadmin_admin_password
        target: admin_password
    volumes:
      # Likely need to change this
      #- pgadmin:/var/lib/pgadmin
      - ${DEV_MOUNT_PGADMIN_SHELL_MIGRATIONS:-$EMPTY_MOUNT}
